### ISSUE TITLE
Add Drupal to ch6-related-technologies.md

### ISSUE THREAD

**Issue by iBobik** [DivanteLtd/microservices-book#3]
How about to add Drupal there?

It is universal content management framework with configurable abstract entities (content, users, config entities, customers, product, orders, … anything what you specify). In version 8 it has been rewritten on top of Symfony and has universal web services API (REST in core, other in contrib), so it can be used as a decoupled system.

For Drupal there is project [Drupal Commerce](http://drupalcommerce.org) what is modules ecosystem for e-commerce use cases. There is also project [Drupal Commerce Kickstart](https://drupalcommerce.org/commerce-kickstart-2) what is Drupal distrubution with "typical e-shop" configured and ready for use or customize.

**Comment by pkarw** [comment]
Sounds good for me. Please feel free to add it to ch6 and create a pull request - I'll merge it to the book!
